import type {Metadata} from "next"
import {GeistMono} from "geist/font/mono"
import "./globals.css"

const geistMono = GeistMono.variable

export const metadata: Metadata = {
  title: "Person segmentation",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={geistMono}>
      <body>
        <main className="flex flex-col items-center py-10 px-8 box-border min-h-100vh">
          {children}
        </main>
      </body>
    </html>
  )
}
