lr0: 0.00729 # initial learning rate (SGD=1E-2, Adam=1E-3)
lrf: 0.00984 # final OneCycleLR learning rate (lr0 * lrf)
momentum: 0.98 # SGD momentum/Adam beta1
weight_decay: 0.00035 # optimizer weight decay 5e-4
warmup_epochs: 4.21385 # warmup epochs (fractions ok)
warmup_momentum: 0.76891 # warmup initial momentum
warmup_bias_lr: 0.1 # warmup initial bias lr
box: 8.30896 # box loss gain
cls: 0.56119 # cls loss gain
hsv_h: 0.00924 # image HSV-Hue augmentation (fraction)
hsv_s: 0.77855 # image HSV-Saturation augmentation (fraction)
hsv_v: 0.45721 # image HSV-Value augmentation (fraction)
degrees: 0.0 # image rotation (+/- deg)
translate: 0.07691 # image translation (+/- fraction)
scale: 0.27453 # image scale (+/- gain)
shear: 0.0 # image shear (+/- deg)
perspective: 0.0 # image perspective (+/- fraction), range 0-0.001
flipud: 0.0 # image flip up-down (probability)
fliplr: 0.32975 # image flip left-right (probability)
mosaic: 0.93325 # image mosaic (probability)
mixup: 0.0 # image mixup (probability)
copy_paste: 0.5 # segment copy-paste (probability)
