dataPipelines:
  dataDownloading:
    uploadToDVC: false
    datasetLink: 'mariarisques/dataset-person-yolos'
    dataDirectory: /Users/nachogris/Desktop/UNI/GCED/QUART/TAED2/LAB/TAED2_YOLOs/data/tmp # This needs to be changed according to the executor
    commitMessage: "Update original data in DVC"
  splitData:
    uploadToDVC: false
    dataDirectory: /Users/nachogris/Desktop/UNI/GCED/QUART/TAED2/LAB/TAED2_YOLOs/data/interim/splitted # This needs to be changed according to the executor
    trainSize: 0.7
    valSize: 0.15
    testSize: 0.15
    commitMessage: "Update splitted data in DVC"
  transformMasks:
    uploadToDVC: false
    dataDirectory: /Users/nachogris/Desktop/UNI/GCED/QUART/TAED2/LAB/TAED2_YOLOs/data/interim/transformed # This needs to be changed according to the executor
    commitMessage: "Update transformed data in DVC"
  createLabels:
    uploadToDVC: false
    dataDirectory: /Users/nachogris/Desktop/UNI/GCED/QUART/TAED2/LAB/TAED2_YOLOs/data/processed # This needs to be changed according to the executor
    commitMessage: "Update final data in DVC"