dataPipelines:
  dataDownloading:
    datasetLink: "mariarisques/dataset-person-yolos"
    dataDirectory: /tmp
  splitData:
    dataDirectory: /interim/splitted
    trainSize: 0.7
    valSize: 0.15
    testSize: 0.15
  transformMasks:
    dataDirectory: /interim/transformed
  createLabels:
    dataDirectory: /processed
